name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Spécifiez la version de Python que vous utilisez

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Installer pytest
        working-directory: python-api-handle-it/app  # Spécifiez le chemin vers votre code Python

      - name: Run tests with pytest
        run: |
          pytest
        #working-directory: python-api-handle-it/app/

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 --exclude=test_my_module.py
        working-directory: python-api-handle-it/app/

      - name: Install radon
        run: pip install radon

      - name: Analyze Cyclomatic Complexity
        run: radon cc -s -a -e "venv/*" .

      - name: Install cpplint
        run: pip install cpplint

      - name: Check Code Duplication
        run: cpplint --recursive .
        

      #- name: Analyze cyclomatic complexity
      #  uses: wemake-services/wemake-python-styleguide@0.15.1
        #with:
          #working-directory: ../python-api-handle-it/app  # Spécifiez le chemin vers votre application Python



      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: python-api-handle-it/app # Spécifiez le chemin vers votre application Python
          push: true
          tags: mansoursou/imageTP3:latest

      - name: Cleanup
        run: |
          docker rmi -f $(docker images -q)
